apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: yoshiunfriendly/frontend-hideyoshi.com:latest
                  limits:
                  ports:
                      - containerPort: 5000
                  env:
                      - name: PORT
                        value: "5000"

                      - name: BACKEND
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: backend-url
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
spec:
    type: NodePort
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
          nodePort: 30100
    selector:
        app: frontend
