apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: yoshiunfriendly/frontend-hideyoshi.com:latest
                  limits:
                  ports:
                      - containerPort: 5000
                  env:
                      - name: PORT
                        value: "5000"

                      - name: BACKEND_URL
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: backend-url

                      - name: BACKEND
                        value: "$(BACKEND_SERVICE_PORT)"
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: portfolio
spec:
    selector:
        app: frontend
    ports:
        - port: 5000
    type: ClusterIP
