apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: portfolio 
    name: backend-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            limits:
            containers:
                - name: backend
                  image: yoshiunfriendly/backend-hideyoshi.com
                  ports:
                      - containerPort: 8070
                  env:
                      - name: FRONT_END_PATH
                        valueFrom:
                            configMapKeyRef:
                                name: frontend-config
                                key: frontend-url

                      - name: FRONT_END_CONNECTION_TYPE
                        valueFrom:
                            configMapKeyRef:
                                name: frontend-config
                                key: frontend-type

                      - name: PORT
                        value: "8070"

                      - name: POSTGRES_URL
                        valueFrom:
                            configMapKeyRef:
                                name: postgres-config
                                key: postgres-url

                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_DB

                      - name: DATABASE_URL
                        value: "postgresql://$(POSTGRES_URL):5432/$(POSTGRES_DB)"

                      - name: DATABASE_USER
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_USER

                      - name: DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
    namespace: portfolio 
    name: backend-service
spec:
    selector:
        app: backend
    ports:
        - port: 8070
          protocol: TCP
          targetPort: 8070
    type: ClusterIP
