apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: letsencrypt-cluster-certificate
    namespace: cert-manager
spec:
    dnsNames:
        - hideyoshi.com.br
        - api.hideyoshi.com.br
        - www.hideyoshi.com.br
        - www.api.hideyoshi.com.br
    secretName: certificate-tls
    issuerRef:
        name: letsencrypt-cluster-issuer
        kind: ClusterIssuer